# Generated by Django 3.2.16 on 2023-11-25 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='reservation_id',
        ),
        migrations.AddField(
            model_name='reservation',
            name='room_number',
            field=models.ForeignKey(db_column='room_number', default='000RM', on_delete=django.db.models.deletion.CASCADE, to='project.room'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
