# Generated by Django 3.2.16 on 2023-11-25 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20231125_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomDetail',
            fields=[
                ('room_type', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('room_capacity_adult', models.IntegerField()),
                ('room_capacity_child', models.IntegerField()),
                ('room_price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'room_detail',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_price',
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(db_column='room_type', on_delete=django.db.models.deletion.CASCADE, to='project.roomdetail'),
        ),
    ]
